layout_spectrum: 0.04596321730800711
typography_spectrum: 0.10903549931694449
color:
  brandStrength: 0.8850839821365432
  lightness: 0.16056243797137154
  saturation: 0.024088473822091623
  rhythmicContrast: 0.16030444691298842
  brandColors:
    - '#FFFFFF'
    - '#0862B2'
    - '#FF0002'
    - '#FF5F67'
    - '#ADADAD'
name: MediaInbox
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FEHSYKwFDCEU%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DEHSYKwFDCEU&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FEHSYKwFDCEU%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: StrokeOfIllusion
          url: 'https://www.youtube.com/user/StrokeOfIllusion'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - audio frequency
        - equalization (audio)
        - dubstep
      description: >-
        Similar to my other Audio Waveform, but with a different song. This time
        it's Daft Punk's End of the Line, remixed by Distrix. The wobbles and
        bass in this gives a better effect overall. For an Open Brief project at
        University.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=EHSYKwFDCEU&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=EHSYKwFDCEU&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=EHSYKwFDCEU&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=EHSYKwFDCEU&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=EHSYKwFDCEU&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=EHSYKwFDCEU'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=EHSYKwFDCEU
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=EHSYKwFDCEU
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=EHSYKwFDCEU'
      title: Audio Waveform EQ 2
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
url: 'https://mediainbox.tech'
author:
  name: Mediainbox
  email: alejandro@mediainbox.net
title: MediaInbox
description: Tech Startup to bring radio to 21th century
purpose:
  - type: contact
    url: 'mailto:alejandro@mediainbox.net'
    label: Contact us!
