layout_spectrum: 0.930202598683536
typography_spectrum: 0.5619288254529238
color:
  brandStrength: 0.676506276242435
  lightness: 0.420977458357811
  saturation: 0.36052025365643203
  rhythmicContrast: 0.28076323540881276
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
name: MediaInbox
content: []
github: true
url: 'https://mediainbox.tech'
author:
  name: Mediainbox
  email: alejandro@mediainbox.net
title: MediaInbox
description: Tech Startup to bring radio to 21th century
