layout_spectrum: 0.04596321730800711
typography_spectrum: 0.10903549931694449
color:
  brandStrength: 0.8850839821365432
  lightness: 0.16056243797137154
  saturation: 0.024088473822091623
  rhythmicContrast: 0.16030444691298842
  brandColors:
    - '#FFFFFF'
    - '#0862B2'
    - '#FF0002'
    - '#FF5F67'
    - '#ADADAD'
name: MediaInbox
content: []
github: true
url: 'https://mediainbox.tech'
author:
  name: Mediainbox
  email: alejandro@mediainbox.net
title: MediaInbox
description: Tech Startup to bring radio to 21th century
purpose:
  - type: contact
    url: 'mailto:alejandro@mediainbox.net'
    label: Contact us!
